name: Build APK

on:
  push:
    branches:
      - main # Cambiar al nombre de tu rama principal

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v2

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.18' # Puedes cambiar a la versión que necesites

    - name: Obtener dependencias
      run: flutter pub get

    - name: Construir APK
      run: flutter build apk --release

    - name: Subir APK como artefacto
      uses: actions/upload-artifact@v2
      with:
        name: app-release
        path: build/app/outputs/flutter-apk/app-release.apk
